config/routes.rb
Rails.application.routes.draw do
  # Shop and Orders
  get "shop", to: "shop#index", as: :shop_index
  post "orders/add_item", to: "orders#add_item", as: :add_to_order
  delete "orders/remove_item/:id", to: "orders#remove_item", as: :remove_from_order
  get "orders/:id/checkout", to: "orders#checkout", as: :checkout_order
  post "orders/:id/attach_to_collection", to: "orders#attach_to_collection", as: :attach_to_collection_order
  post "orders/:id/mark_delivered", to: "orders#mark_delivered", as: :mark_delivered_order
  namespace :admin do
    resources :bulk_messages, only: [:index]
    resources :logistics, only: :index
    resources :collections, only: [:index, :edit, :update, :destroy]
    resources :discount_codes, only: [:index, :new, :create, :show]
    resources :products, only: [:index, :new, :create, :edit, :update]
    resources :drop_off_sites do
      member do
        post :create_event
      end
      collection do
        post :create_next_week_events
      end
    end
    resources :users, only: [:index, :new, :create, :edit, :update, :show] do
      post :renew_last_subscription, on: :member
    end
  end

  post 'snapscan/webhook', to: 'payments#snapscan_webhook'

  # payments
  # resources :webhooks, only: :create
  get 'snapscan/payments', to: 'payments#fetch_snapscan_payments'
  resources :payments, only: :index

  # users
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # drop-off site managers
  resources :drop_off_site_managers, only: [:index, :show, :edit, :update]

  patch 'optimise_route', to: 'collections#optimise_route'
  post "perform_create_today_collections", to: "collections#perform_create_today_collections"
  post "perform_create_next_week_collections", to: "collections#perform_create_next_week_collections"
  # Defines getting the csv - the form then sends the data to the import_csv route
  resources :collections, only: [:edit, :update, :destroy] do
    member do
      post :add_bags
      post :remove_bags
      post :add_customer_note
      put :update_position
    end
    collection do
      get :this_week
      patch :skip_today
      get :export_csv
      get :load_csv
      post :import_csv
    end
  end

  resources :invoices do
    member do
      get :paid
      patch :issued_bags, to: "invoices#issued_bags"
      get :send_email, to: "invoices#send_email"
      post :apply_discount_code
    end
    collection do
      get "bags/:bags", to: "invoices#bags", as: :bag

    end
  end

  resources :quotations do
    member do
      get :send_email
      get :pdf
    end
  end

  # resources create all the CRUD routes for a model - here I am nesting new and create collection methods under subscriptions
  resources :subscriptions do
    resource :business_profile, only: [:new, :create, :edit, :update]
    resources :collections, only: %i[new create]
    # - here I am creating /subscriptions/today
    collection do
      get :add_locations
      post :create_locations
      get :today
      get :recently_lapsed
      get :export
      get :update_end_date
      post :import_csv
      get :pending
      get :all
      get :paused
      get :completed
      get :legacy
    end
    member do
      get :want_bags
      get :collections
      get :welcome
      get :welcome_invoice
      post :pause
      # route to unpause subscription
      post :unpause
      # route to clear holiday
      post :clear_holiday
      patch :holiday_dates
      get :complete
      post :reassign_collections
      post :collect_courtesy
    end
  end
  get '/today/notes', to: 'subscriptions#today_notes', as: :today_notes

  # I want get and patch requests on these custom drivers_day routes
  # member routes are created with /drivers_day/:id/custom_route
  # these routes (the get and the patch) allow for form input to the instance of drivers day at each url
  resources :drivers_days do
    collection do
      get :route
    end
    member do
      get :vamos
      get :complete
      get :start
      patch :start
      get :end
      patch :end
      get :collections
      get :snapshot
    end
    resources :collections, only: [:index] do
      collection do
        post :reset_order
      end
    end
    resources :buckets, only: [:index, :create, :destroy]
    resources :drop_off_events, only: [:index, :show, :edit, :update] do
      member do
        post :complete
      end
      resources :buckets, only: [:create, :destroy], controller: 'drop_off_events/buckets'
    end
  end

  resources :collections do
    member do
      get :issue_bags
    end
  end

  resources :interests, only: :create

  # customers
  get "my_subscriptions", to: "customers#subscriptions"
  get "manage", to: "customers#manage"
  get "account", to: "customers#account"
  get "collections_history", to: "customers#collections_history"
  get "skipme", to: "customers#skipme"
  get "welcome", to: "customers#welcome"
  get "referrals", to: "customers#referrals"

  # static pages
  root "pages#home"
  get "story", to: "pages#story"

  # farms (public-facing drop-off sites)
  resources :farms, only: [:index, :show], param: :slug



  # Block WordPress scanning bots
  match "/wp-includes/*path", to: ->(_) { [404, {}, ["Not Found"]] }, via: :all
  match "/blog/wp-includes/*path", to: ->(_) { [404, {}, ["Not Found"]] }, via: :all
  match "/web/wp-includes/*path", to: ->(_) { [404, {}, ["Not Found"]] }, via: :all

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/views/shared/_admin_navbar.html.erb
<div class="navbar-container">
  <div class="inner-container">
    <%= link_to root_path do %>
      <%= image_tag('gooi_logo_CR.png', class: 'gooi-logo') %>
    <% end %>
    <div class="links-container">
      <%= link_to 'subscriptions', subscriptions_path, class:"link-title" %>
      <%= link_to 'invoices', invoices_path, class:"link-title" %>
      <%= link_to 'quotations', quotations_path, class:"link-title" %>
      <%= link_to 'users', admin_users_path, class:"link-title" %>
      <%= link_to 'products', admin_products_path, class:"link-title" %>
      <%= link_to 'discounts', admin_discount_codes_path, class:"link-title" %>
      <%= link_to 'bulk messages', admin_bulk_messages_path, class:"link-title" %>
      <%= link_to 'drop-offs', admin_drop_off_sites_path, class:"link-title" %>
      <%= link_to 'drivers days', drivers_days_path, class:"link-title" %>
      <%= link_to 'collections', this_week_collections_path, class:"link-title" %>

      <% if user_signed_in?  %>
        <div class="sign-up-btn">
          <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete} %>
        </div>
      <% else %>
        <div class="sign-up-btn">
          <%= link_to "Log in", new_user_session_path %>
        </div>
      <% end %>
    </div>
    <div class="hamburger-menu">
      <div id="menu-icon">
      </div>
      <ul>
        <li class="nav-item dropdown">
          <%= image_tag 'menu-svgrepo-com.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to 'subscriptions', subscriptions_path, class: "dropdown-item" %>
            <%= link_to 'invoices', invoices_path, class: "dropdown-item" %>
            <%= link_to 'quotations', quotations_path, class: "dropdown-item" %>
            <%#= link_to 'payments', payments_path, class:"dropdown-item" %>
            <%= link_to 'users', admin_users_path, class:"dropdown-item" %>
            <%= link_to 'products', admin_products_path, class:"dropdown-item" %>
            <%= link_to 'discounts', admin_discount_codes_path, class:"dropdown-item" %>
            <%= link_to 'bulk messages', admin_bulk_messages_path, class:"dropdown-item" %>
            <%= link_to 'drop-offs', admin_drop_off_sites_path, class:"dropdown-item" %>
            <%= link_to 'drivers days', drivers_days_path, class:"dropdown-item" %>
            <%= link_to 'collections', this_week_collections_path, class:"dropdown-item" %>
            <% if user_signed_in? %>
              <%= link_to "log out", destroy_user_session_path,
                  data: { turbo_method: :delete }, class: "dropdown-item" %>
            <% else %>
              <%= link_to 'Log in', new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_customer_navbar.html.erb
<div class="navbar-container">
  <div class="inner-container">
    <%= link_to root_path do %>
      <%= image_tag('gooi_logo_CR.png', class: 'gooi-logo', alt: 'Gooi') %>
    <% end %>

    <!-- Hamburger always visible -->
    <div class="hamburger-menu dropdown ms-auto">
      <%= link_to shop_index_path do %>
        <i class="fa-solid fa-cart-shopping"></i>
      <% end %>
      <button class="btn p-2 border-0 bg-transparent" id="navMenuButton"
              data-bs-toggle="dropdown" aria-expanded="false" aria-label="Open menu">
        <i class="fa-solid fa-bars fa-2x" style="color:#023f3a;"></i>
      </button>

      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navMenuButton">
        <li><%= link_to 'Manage', manage_path, class: "dropdown-item" %></li>
        <li><%= link_to 'Account', account_path, class: "dropdown-item" %></li>
        <li><%= link_to 'Subscriptions', my_subscriptions_path, class: "dropdown-item" %></li>
        <li><%= link_to 'Referrals', referrals_path, class: "dropdown-item" %></li>
        <% if current_user.respond_to?(:invoices) && current_user.invoices.any? %>
          <li><%= link_to "Invoices", invoices_path, class: "dropdown-item" %></li>
        <% end %>

        <li><hr class="dropdown-divider"></li>

        <% if user_signed_in? %>
          <li>
            <%= link_to "Log out", destroy_user_session_path,
                        class: "dropdown-item text-danger",
                        data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path, class: "dropdown-item" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_driver_navbar.html.erb
<div class="navbar navbar-expand-sm pt-4">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('gooi_logo_CR.png', alt: 'Your Logo', class: 'alt-logo') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? && current_user.driver? %>
          <% dd = nav_drivers_day %>

          <li class="nav-item active">
            <%= link_to "Welcome", (dd ? vamos_drivers_day_path(dd) : "#"),
        class: "nav-link #{'disabled' unless dd}", aria: { disabled: (!dd).to_s } %>
          </li>

          <li class="nav-item active">
            <%= link_to "Start the Day", (dd ? start_drivers_day_path(dd) : "#"),
        class: "nav-link #{'disabled' unless dd}", aria: { disabled: (!dd).to_s } %>
          </li>

          <li class="nav-item active">
            <%= link_to "Today's List", today_subscriptions_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "Drop-Offs", (dd ? drivers_day_drop_off_events_path(dd) : "#"),
        class: "nav-link #{'disabled' unless dd}", aria: { disabled: (!dd).to_s } %>
          </li>

          <li class="nav-item active">
            <%= link_to "End the Day", (dd ? end_drivers_day_path(dd) : "#"),
        class: "nav-link #{'disabled' unless dd}", aria: { disabled: (!dd).to_s } %>
          </li>
  
        <li class="nav-item">
          <%= link_to "Log Out",destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/shared/_drop_off_navbar.html.erb
<div class="navbar navbar-expand-sm pt-4">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('gooi_logo_CR.png', alt: 'Alfred\'s Gooi Logo', class: 'alt-logo') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto display-flex align-items-end">
        <% if user_signed_in? && current_user.drop_off? %>
          <% if current_user.drop_off_sites.any? %>
            <li class="nav-item">
              <%= link_to "Farm", drop_off_site_manager_path(current_user.drop_off_sites.first), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Account", edit_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>Connect with us</p>
  <div class="footer-links">
    <%= link_to "https://www.instagram.com/gooi_capetown/", class: 'icon-link', target: '_blank' do %>
      <i class="fa-brands fa-instagram"></i>
    <% end %>
    <%= link_to "https://www.facebook.com/gooicapetown/", class: 'icon-link', target: '_blank' do %>
      <i class="fa-brands fa-facebook-f"></i>
    <% end %>
    <%= link_to "https://wa.me/+27785325513", class: 'icon-link', target: '_blank' do %>
      <i class="fa-brands fa-whatsapp"></i>
    <% end %>
    <%= link_to "mailto:gooicapetown@gmail.com", class: 'icon-link', target: '_blank' do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>
  </div>
</footer>

app/views/shared/_ios_pwa_links.html.erb
<!--<link rel="apple-touch-icon" sizes="57x57" href="<%#= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%#= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%#= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%#= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%#= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%#= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%#= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%#= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%#= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%#= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%#= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%#= image_path 'icons/favicon-16x16.png' %>">
-->

app/views/shared/_navbar.html.erb
<!--<div class=navbar>-->
<%#= link_to root_path do %>
  <%#= image_tag('alt_logo.jpg', alt: 'Your Logo', class: 'alt_logo') %>
  <%# end %>
  <%# if user_signed_in? %>
  <!--    <div class="flex-nav">-->
  <%#= link_to "Home", root_path, class: 'logout-link' %>
  <%#= link_to "Today", today_subscriptions_path, class: 'logout-link' %>
  <%#= link_to "load CSV", get_csv_path, class: 'logout-link' %>
  <!--      <br>-->
  <%#= link_to "LOGOUT", destroy_user_session_path, data: {turbo_method: :delete}, class: 'logout-link' %>
  <!--    </div>-->
  <%# else %>
  <!--    <div>-->
  <%#= link_to "Login", new_user_session_path, class: 'logout-link' %>
  <!--    </div>-->
  <%# end %>
  <!--</div>
-->
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon pt-4">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag('gooi_logo_CR.png', alt: 'Your Logo', class: 'alt-logo') %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <% drivers_day = DriversDay.find_by(date: Date.today) %>
            <%= drivers_day %>
            <% if current_user.driver? %>
              <li class="nav-item active">
                <%= link_to "Welcome", drivers_day.present? ? 1rivers_day_path(drivers_day) : "#", class: "nav-link #{'disabled' unless drivers_day}" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Start the Day", drivers_day.present? ? start_drivers_day_path(drivers_day) : "#", class: "nav-link #{'disabled' unless drivers_day}" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Today's List", today_subscriptions_path, class: "nav-link" %>
              </li>
              <!-- <li class="nav-item active">-->
              <%#= link_to "Drop Off Page", drivers_day.present? ? drop_off_drivers_day_path(drivers_day) : "#", class: "nav-link #{'disabled' unless drivers_day}" %>
              <!--              </li>-->
              <li class="nav-item active">
                <%= link_to "End the Day", drivers_day.present? ? end_drivers_day_path(drivers_day) : "#", class: "nav-link #{'disabled' unless drivers_day}" %>
              </li>
            <% elsif current_user.admin? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Collections
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Load CSV", load_csv_collections_path, class: "dropdown-item" %>
                  <%= link_to "Export CSV", export_csv_collections_path, class: "dropdown-item" %>
                  <%= link_to "Today", today_subscriptions_path, class: "dropdown-item" %>
                  <%= link_to "Tomorrow", tomorrow_subscriptions_path, class: "dropdown-item" %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Subscriptions
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Subscriptions", subscriptions_path, class: "dropdown-item" %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Drivers Days
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Drivers Days", drivers_days_path, class: "dropdown-item" %>
                  <%= link_to "Today's List", today_subscriptions_path, class: "dropdown-item" %>
                  <%#= link_to "Drop Off Page", drop_off_drivers_day_path(drivers_day), class: "dropdown-item" %>
                  <% if drivers_day %>
                    <%= link_to "End the Day", end_drivers_day_path(drivers_day), class: "dropdown-item" %>
                  </div>
                </li>
              <% end %>
            <% elsif current_user.customer? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Subscription
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "New", new_subscription_path, class: "dropdown-item" %>
                  <% current_user.subscriptions.each do |subscription| %>
                    <%= link_to "Edit #{subscription.street_address}", edit_subscription_path(subscription), class: "dropdown-item" %>
                  <% end %>
                </div>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "LOGOUT",destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_new_navbar.html.erb
<div class="navbar-container">
  <div class="inner-container">
    <%= link_to root_path do %>
      <%= image_tag('gooi_logo_CR.png', class: 'gooi-logo') %>
    <% end %>
    <!--<div class="links-container">-->
      <%#= link_to 'The story', story_path, class:"link-title" %>
      <%#= link_to 'How we compost', root_path, class: "link-title" %>
      <% if user_signed_in?  %>
        <div class="sign-up-btn">
          <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete} %>
        </div>
      <% else %>

          <%= link_to "Log in", new_user_session_path, class:"submit-btn", style:"margin:1.9rem" %>

      <% end %>
    <!--</div>-->

  </div>
</div>